'use client';

import { useState, useEffect, useRef } from 'react';
import { createClientComponentClient } from '@supabase/auth-helpers-nextjs';
import { useTheme } from 'next-themes'; 
import { Line, Doughnut } from 'react-chartjs-2';
import jsPDF from 'jspdf'; 
import autoTable from 'jspdf-autotable'; 
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  ArcElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';
import styles from './AdminDashboard.module.css'; 

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, ArcElement, Title, Tooltip, Legend);

export default function AdminDashboard() {
  const supabase = createClientComponentClient();
  const { resolvedTheme } = useTheme();
  const [loading, setLoading] = useState(true);
  
  // --- PDF & Export State ---
  const [showExportModal, setShowExportModal] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  
  // Toggles & Chart Refs
  const [includeCharts, setIncludeCharts] = useState(true); 
  const lineChartRef = useRef(null); 
  const pieChartRef = useRef(null);

  // --- Data State ---
  const [adminName, setAdminName] = useState('Administrator'); // 🟢 Store Admin Name
  const [stats, setStats] = useState({ interns: 0, companies: 0, jobs: 0, applications: 0 });
  const [lineData, setLineData] = useState(null);
  const [pieData, setPieData] = useState(null);
  const [tableData, setTableData] = useState([]); 

  // 🟢 Date Ranges for PDF
  const [dateRanges, setDateRanges] = useState({
    overall: 'N/A',
    jobs: 'N/A',
    apps: 'N/A'
  });

  const chartTextColor = resolvedTheme === 'dark' ? '#F8FAFC' : '#1e293b';
  const chartGridColor = resolvedTheme === 'dark' ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.1)';

  useEffect(() => {
    const fetchDashboardData = async () => {
      try {
        // 1. Fetch Admin Profile for Report "Generated By"
        const { data: { user } } = await supabase.auth.getUser();
        if (user) {
          const { data: profile } = await supabase.from('profiles').select('full_name').eq('id', user.id).single();
          if (profile?.full_name) setAdminName(profile.full_name);
        }

        // 2. Counts
        const { count: internCount } = await supabase.from('profiles').select('*', { count: 'exact', head: true }).eq('user_type', 'student'); 
        const { count: companyCount } = await supabase.from('companies').select('*', { count: 'exact', head: true });
        const { count: jobCount } = await supabase.from('job_posts').select('*', { count: 'exact', head: true });
        const { count: appCount } = await supabase.from('job_applications').select('*', { count: 'exact', head: true });

        setStats({
          interns: internCount || 0,
          companies: companyCount || 0,
          jobs: jobCount || 0,
          applications: appCount || 0
        });

        // 3. Fetch Raw Data for Charts & Date Calculation
        const { data: jobRaw } = await supabase.from('job_posts').select('created_at').order('created_at', { ascending: true });
        const { data: appRaw } = await supabase.from('job_applications').select('created_at').order('created_at', { ascending: true });
        
        // 🟢 Helper to calculate date strings
        const calculateRange = (data) => {
          if (!data || data.length === 0) return 'No Data';
          const start = new Date(data[0].created_at).toLocaleDateString();
          const end = new Date(data[data.length - 1].created_at).toLocaleDateString();
          return `${start} - ${end}`;
        };

        const jobRangeStr = calculateRange(jobRaw);
        const appRangeStr = calculateRange(appRaw);
        
        // Calculate "Overall" range (earliest of both to latest of both)
        const allDates = [...(jobRaw || []), ...(appRaw || [])].sort((a,b) => new Date(a.created_at) - new Date(b.created_at));
        const overallRangeStr = calculateRange(allDates);

        setDateRanges({
          overall: overallRangeStr,
          jobs: jobRangeStr,
          apps: appRangeStr
        });

        // Process Charts
        const processByMonth = (data) => {
          const months = {};
          data?.forEach(item => {
            const date = new Date(item.created_at);
            const key = date.toLocaleString('default', { month: 'short' }); 
            months[key] = (months[key] || 0) + 1;
          });
          return months;
        };
        const jobsByMonth = processByMonth(jobRaw || []);
        const appsByMonth = processByMonth(appRaw || []);
        const allMonths = [...new Set([...Object.keys(jobsByMonth), ...Object.keys(appsByMonth)])];
        
        setLineData({
          labels: allMonths,
          datasets: [
            {
              label: 'New Jobs',
              data: allMonths.map(m => jobsByMonth[m] || 0),
              borderColor: '#EE7428', 
              backgroundColor: 'rgba(238, 116, 40, 0.2)',
              tension: 0.4,
            },
            {
              label: 'Applications',
              data: allMonths.map(m => appsByMonth[m] || 0),
              borderColor: '#00d4ff',
              backgroundColor: 'rgba(0, 212, 255, 0.2)',
              tension: 0.4,
            }
          ],
        });

        const { data: jobTypes } = await supabase.from('job_posts').select('work_setup');
        const typeCounts = { 'Remote': 0, 'On-site': 0, 'Hybrid': 0 };
        jobTypes?.forEach(job => {
            const setup = job.work_setup || 'On-site';
            if (typeCounts[setup] !== undefined) typeCounts[setup]++;
            else typeCounts['On-site']++;
        });

        setPieData({
          labels: Object.keys(typeCounts),
          datasets: [{
              data: Object.values(typeCounts),
              backgroundColor: ['#EE7428', '#00d4ff', resolvedTheme === 'dark' ? '#F8FAFC' : '#94a3b8'], 
              borderWidth: 0,
          }],
        });

        // 4. Fetch Table Data (Recent Logs)
        const { data: rawApps } = await supabase
          .from('job_applications')
          .select('*') 
          .order('created_at', { ascending: false })
          .limit(15);

        if (rawApps && rawApps.length > 0) {
           const firstItem = rawApps[0];
           const applicantKey = 'intern_id' in firstItem ? 'intern_id' : 'user_id';
           const jobKey = 'job_id' in firstItem ? 'job_id' : 'post_id';

           const internIds = [...new Set(rawApps.map(a => a[applicantKey]).filter(Boolean))];
           const jobIds = [...new Set(rawApps.map(a => a[jobKey]).filter(Boolean))];

           const { data: users } = await supabase.from('profiles').select('*').in('id', internIds);
           const { data: jobs } = await supabase.from('job_posts').select('*').in('id', jobIds);

           const detailedApps = rawApps.map(app => {
             const user = users?.find(u => u.id === app[applicantKey]);
             const job = jobs?.find(j => j.id === app[jobKey]);
             
             let userName = 'Unknown User';
             if (user) {
                 if (user.fullname) userName = user.fullname;
                 else if (user.full_name) userName = user.full_name;
                 else if (user.first_name) userName = `${user.first_name} ${user.last_name || ''}`;
                 else if (user.email) userName = user.email;
             }
             const jobTitle = job ? (job.job_title || job.title || 'No Title') : 'Unknown Job';

             return {
               ...app,
               profiles: { full_name: userName },
               job_posts: { job_title: jobTitle }
             };
           });
           setTableData(detailedApps);
        } else {
           setTableData([]);
        }

      } catch (error) {
        console.error("Dashboard Load Error:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchDashboardData();
  }, [supabase, resolvedTheme]);


  // --- 🟢 PDF EXPORT LOGIC ---
  const handleDownloadPDF = async () => {
    setIsGenerating(true);

    try {
      const doc = new jsPDF('p', 'mm', 'a4');
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const today = new Date().toLocaleDateString();

      // --- A. STYLES (Clear, B&W, High Contrast) ---
      const bwStyles = {
        theme: 'grid', // Grid creates borders for clarity
        headStyles: { 
          fillColor: [30, 30, 30], // Dark Charcoal
          textColor: [255, 255, 255], 
          fontStyle: 'bold',
          halign: 'center'
        },
        styles: { 
          fontSize: 10, 
          cellPadding: 4, 
          textColor: [0, 0, 0], 
          lineColor: [150, 150, 150], // Visible borders
          lineWidth: 0.1,
        },
        margin: { top: 20, bottom: 20 },
      };

      // Header & Footer Helper
      const addHeaderFooter = (pageNumber, totalPages) => {
        // Top Left: InternLink
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(0, 0, 0);
        doc.text("InternLink", 14, 12);

        // Top Right: Date
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100);
        doc.text(`Report Date: ${today}`, pageWidth - 14, 12, { align: 'right' });

        // Footer
        doc.setFontSize(8);
        doc.text(`Page ${pageNumber} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
        doc.text("InternLink Analytics System", 14, pageHeight - 10);
      };

      // --- B. DOCUMENT HEADER ---
      let currentY = 25;

      // Title
      doc.setFontSize(22);
      doc.setTextColor(0);
      doc.text("Analytics Report", 14, currentY);
      currentY += 8;

      // Generated By info
      doc.setFontSize(11);
      doc.setTextColor(80);
      doc.text(`Generated by: ${adminName}`, 14, currentY);
      currentY += 15; // Gap before tables

      // --- C. TABLE 1: KPI OVERVIEW ---
      doc.setFontSize(14);
      doc.setTextColor(0);
      doc.text("1. General Overview", 14, currentY);
      
      // Date Range Subtitle
      doc.setFontSize(9);
      doc.setTextColor(100);
      doc.text(`Data Range: ${dateRanges.overall}`, 150, currentY, { align: 'right' }); // Right aligned next to title
      currentY += 6;

      autoTable(doc, {
        startY: currentY,
        head: [['Total Interns', 'Companies', 'Active Listings', 'Total Applications']],
        body: [[stats.interns, stats.companies, stats.jobs, stats.applications]],
        ...bwStyles,
        styles: { ...bwStyles.styles, halign: 'center' }
      });
      currentY = doc.lastAutoTable.finalY + 15;


      // --- D. TABLE 2: TRENDS (Data) ---
      doc.setFontSize(14);
      doc.setTextColor(0);
      doc.text("2. Platform Activity Data", 14, currentY);
      
      doc.setFontSize(9);
      doc.setTextColor(100);
      doc.text(`Data Range: ${dateRanges.overall}`, 150, currentY, { align: 'right' });
      currentY += 6;

      const trendsBody = lineData ? lineData.labels.map((month, i) => [
        month,
        lineData.datasets[0].data[i], 
        lineData.datasets[1].data[i] 
      ]) : [];

      autoTable(doc, {
        startY: currentY,
        head: [['Month', 'New Jobs', 'Applications']],
        body: trendsBody,
        ...bwStyles,
        styles: { ...bwStyles.styles, halign: 'center' }
      });
      currentY = doc.lastAutoTable.finalY + 15;


      // --- E. TABLE 3: JOB TYPES (Data) ---
      if (currentY > pageHeight - 40) { doc.addPage(); currentY = 25; }
      
      doc.setFontSize(14);
      doc.setTextColor(0);
      doc.text("3. Job Types Distribution", 14, currentY);

      doc.setFontSize(9);
      doc.setTextColor(100);
      doc.text(`Data Range: ${dateRanges.jobs}`, 150, currentY, { align: 'right' });
      currentY += 6;

      const pieHead = pieData ? pieData.labels : ['Remote', 'On-site', 'Hybrid'];
      const pieBody = pieData ? [pieData.datasets[0].data] : [[0, 0, 0]];

      autoTable(doc, {
        startY: currentY,
        head: [pieHead],
        body: pieBody,
        ...bwStyles,
        styles: { ...bwStyles.styles, halign: 'center' }
      });
      currentY = doc.lastAutoTable.finalY + 15;


      // --- F. TABLE 4: RECENT LOGS ---
      if (currentY > pageHeight - 40) { doc.addPage(); currentY = 25; }
      
      doc.setFontSize(14);
      doc.setTextColor(0);
      doc.text("4. Recent Applications Log", 14, currentY);

      doc.setFontSize(9);
      doc.setTextColor(100);
      doc.text(`Data Range: ${dateRanges.apps}`, 150, currentY, { align: 'right' });
      currentY += 6;

      const activityBody = tableData.map(row => [
        new Date(row.created_at).toLocaleDateString(),
        row.profiles?.full_name || 'Unknown',
        row.job_posts?.job_title || 'Unknown',
        row.status || 'Pending'
      ]);

      autoTable(doc, {
        startY: currentY,
        head: [['Date', 'Applicant Name', 'Job Title', 'Status']],
        body: activityBody,
        ...bwStyles,
        // Make this table striped for long lists, but still B&W
        theme: 'striped', 
        headStyles: { fillColor: [30, 30, 30], textColor: 255 },
        styles: { ...bwStyles.styles, halign: 'left' },
      });
      currentY = doc.lastAutoTable.finalY + 20;


      // --- G. CHARTS (IF ENABLED) - PLACED AT THE BOTTOM ---
      if (includeCharts) {
        doc.addPage(); 
        currentY = 25; // Reset Y for new page

        doc.setFontSize(16);
        doc.setTextColor(0);
        doc.text("Data Visualizations", 14, currentY);
        currentY += 10;

        // 1. Line Chart
        if (lineChartRef.current) {
          doc.setFontSize(12);
          doc.text("Platform Trends (Visual)", 14, currentY);
          currentY += 5;

          const chartBase64 = lineChartRef.current.toBase64Image(); 
          const imgWidth = 170; 
          const imgHeight = 85;
          doc.addImage(chartBase64, 'PNG', (pageWidth - imgWidth) / 2, currentY, imgWidth, imgHeight);
          currentY += imgHeight + 15;
        }

        // 2. Pie Chart
        if (pieChartRef.current) {
          // Check if space exists, else new page
          if (currentY + 100 > pageHeight) { doc.addPage(); currentY = 25; }

          doc.setFontSize(12);
          doc.text("Job Types (Visual)", 14, currentY);
          currentY += 5;

          const chartBase64 = pieChartRef.current.toBase64Image();
          const imgWidth = 90;
          const imgHeight = 90;
          doc.addImage(chartBase64, 'PNG', (pageWidth - imgWidth) / 2, currentY, imgWidth, imgHeight);
        }
      }

      // --- H. APPLY HEADER/FOOTER TO ALL PAGES ---
      const totalPages = doc.internal.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        addHeaderFooter(i, totalPages);
      }

      doc.save(`InternLink_Report_${new Date().toISOString().split('T')[0]}.pdf`);
      setShowExportModal(false);

    } catch (err) {
      console.error("PDF Failed", err);
      alert("Could not generate PDF");
    } finally {
      setIsGenerating(false);
    }
  };

  if (loading) return <div className={styles.loadingContainer}>Loading...</div>;

  return (
    <div className={styles.dashboardWrapper}>
      <div className={styles.header}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <h1 className={styles.title}>Dashboard Overview</h1>
            <p className={styles.subtitle}>Welcome back, {adminName}.</p>
          </div>
          <button className={styles.exportBtn} onClick={() => setShowExportModal(true)}>
            Export PDF Report
          </button>
        </div>
      </div>

      <div className={styles.printArea}>
        {/* KPI Cards */}
        <div className={styles.kpiGrid}>
          <StatCard title="Total Interns" value={stats.interns} change="Active" type="positive" />
          <StatCard title="Companies" value={stats.companies} change="Verified" type="neutral" />
          <StatCard title="Active Listings" value={stats.jobs} change="Live" type="positive" />
          <StatCard title="Total Applications" value={stats.applications} change="Total" type="neutral" />
        </div>

        {/* Charts */}
        <div className={styles.chartsGrid}>
          <div className={styles.chartCard}>
            <h3 className={styles.chartTitle}>Platform Trends</h3>
            <div className={styles.chartContainer}>
              {/* Line Chart with Ref */}
              {lineData && <Line ref={lineChartRef} 
                  data={lineData} 
                  options={{ 
                      responsive: true, 
                      maintainAspectRatio: false,
                      scales: {
                          y: { ticks: { color: chartTextColor }, grid: { color: chartGridColor } },
                          x: { ticks: { color: chartTextColor }, grid: { display: false } }
                      },
                      plugins: { legend: { labels: { color: chartTextColor } } }
                  }} 
              />}
            </div>
          </div>

          <div className={styles.chartCard}>
            <h3 className={styles.chartTitle}>Job Types</h3>
            <div className={styles.pieContainer}>
               {/* Pie Chart with Ref */}
              {pieData && <Doughnut ref={pieChartRef} 
                  data={pieData} 
                  options={{ 
                      responsive: true, 
                      maintainAspectRatio: false,
                      plugins: { legend: { position: 'bottom', labels: { color: chartTextColor } } }
                  }} 
              />}
            </div>
          </div>
        </div>
      </div> 

      {/* Export Modal */}
      {showExportModal && (
        <div className={styles.modalOverlay}>
          <div className={styles.modalContent}>
            <h3>Export Analytics Report?</h3>
            <p>Generate a structured PDF report of your current dashboard data.</p>
            
            <div style={{ margin: '20px 0', textAlign: 'left', background: 'var(--bg-input)', padding: '15px', borderRadius: '8px' }}>
              <label style={{ display: 'flex', alignItems: 'center', gap: '10px', cursor: 'pointer', color: 'var(--text-main)' }}>
                <input 
                  type="checkbox" 
                  checked={includeCharts} 
                  onChange={(e) => setIncludeCharts(e.target.checked)} 
                  style={{ width: '18px', height: '18px' }}
                />
                <span style={{ fontWeight: 500 }}>Include Visual Charts</span>
              </label>
              <p style={{ fontSize: '12px', color: 'var(--text-muted)', marginLeft: '28px', marginTop: '4px' }}>
                Charts will be appended at the end of the report.
              </p>
            </div>

            <div className={styles.modalActions}>
              <button className={styles.cancelBtn} onClick={() => setShowExportModal(false)}>Cancel</button>
              <button className={styles.confirmBtn} onClick={handleDownloadPDF} disabled={isGenerating}>
                {isGenerating ? 'Generating...' : 'Download Report'}
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}

function StatCard({ title, value, change, type }) {
  const changeClass = type === 'positive' ? styles.positive : styles.neutral;
  return (
    <div className={styles.statCard}>
      <h4 className={styles.statTitle}>{title}</h4>
      <div className={styles.statRow}>
        <span className={styles.statValue}>{value}</span>
        <span className={`${styles.statChange} ${changeClass}`}>{change}</span>
      </div>
    </div>
  );
}